on:
    release:
        types:
            - released

name: Publish the Extension to OpenVSX

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            - run: npm ci
            - run: npm install -g gulp ovsx
            - run: gulp 'vsix:release:package:platform-specific'

            - name: Get package version
              run: node -e "console.log('VERSION=' + require('./package.json').version)" >> $GITHUB_ENV

            - run: ovsx publish --packagePath $(find . -iname *.vsix) -p ${{ secrets.OPEN_VSX_TOKEN }}
